### ISSUE TITLE
xrandr defunct child process

### ISSUE THREAD

**Issue by tmpm697** [jD91mZM2/xidlehook#22]
I saw several xrandr defunct child process of xidlehook but idk how to trace this problem, is there anything I can help or know why xidlehook spawn some dead xrandr processes?

**Comment by jD91mZM2** [comment]
This is probably because I never `wait` for processes to finish, but rather spawn them async (see [src/main.rs#L345-L353](https://github.com/jD91mZM2/xidlehook/blob/master/src/main.rs#L345-L353)). I need to hook the processes up to `mio` so I can get events whenever one of them dies. I'll do this once I get time!

**Comment by jD91mZM2** [comment]
Should be fixed in commit 1315fa9ce883efe2d8868f74b7bb3d47c97a3ca3. Let me know if this works for you and I'll make a patch release

**Comment by tmpm697** [comment]
I try to install xidlehook with `cargo install --git https://github.com/jD91mZM2/xidlehook.git --force` but seems `cargo` used `tags 0.7` to install xidlehook: `Installing xidlehook v0.7.0 (https://github.com/jD91mZM2/xidlehook.git#1315fa9c)`

Is there a way to install with latest commit from git repo?
