### ISSUE TITLE
Disabling timer with xidlehook-client has no effect

### ISSUE THREAD

**Issue by desbma** [jD91mZM2/xidlehook#35]
Start xidlehook with a timer to run `date` after 1s of inactivity:
```
$ xidlehook --socket /tmp/socket --timer 1 "date" ""
```

Disable the timer:
```
$ xidlehook-client --socket /tmp/socket control --timer 0 --action disable
Empty
```

Check it is disabled:
```
$ xidlehook-client --socket /tmp/socket query
QueryResult(
    [
        QueryResult {
            timer: 0,
            time: 1s,
            activation: [
                "/bin/sh",
                "-c",
                "date",
            ],
            abortion: [],
            deactivation: [],
            disabled: true,
        },
    ],
)
```

However the timer still fires after 1s of inactivity....

I'm using xidlehook version 0.8.1 on Arch Linux.

**Comment by jD91mZM2** [comment]
Oh my, I can reproduce this. That's not very great, clearly I have too few tests :(

**Comment by jD91mZM2** [comment]
The issue seems to be that it's the very first timer! It opens some interesting questions about functionality:

- Should the first timer then be ignored even in the cases where it's normally used to calculate the maximum time allowed to sleep (if the first timer activates after 1 hour, and the second timer after 2, the maximum is still 1 because the user could interrupt the 2 hour wait and therefore re-set at 1).
- What about when all timers are disabled? Should xidlehook complain, sleep for all eternity, or keep looping like crazy?

**Comment by jD91mZM2** [comment]
There we go, feel free to try the latest git commit :)

**Comment by desbma** [comment]
Well it now "works", but not the way I would have expected.

Disabling the timer makes xidlehook exit, and I would have prefer if it continues to run until I re-enable the timer.

Otherwise I could have just killed xidlehook, which is much simpler than using the socket API.

**Comment by jD91mZM2** [comment]
I guess that's a good point, sleeping forever it is!

**Comment by jD91mZM2** [comment]
How about https://github.com/jD91mZM2/xidlehook/commit/ad0cc349edffa19e9a93e71b5c48e6a09335dfc6?

**Comment by desbma** [comment]
Works perfectly, thank you very much !

**Comment by desbma** [comment]
@jD91mZM2 Can you please make a 0.8.2 release, so that the fix is available in a tagged release?
Thanks !

**Comment by jD91mZM2** [comment]
Ah yeah, I forgot :|
Will do ASAP, although this weekend I am without computer :(

**Comment by jD91mZM2** [comment]
And of course I forgot. :|

Sorry @desbma!! Will do

**Comment by jD91mZM2** [comment]
Released!
